### ISSUE TITLE
Registering the plugin with my GIMP 2.10 on macOS 10.15.7

### ISSUE THREAD

**Issue by PALYGAP** [Shriinivas/gimpsegany#1]
Thanks for the plugin, though I am having trouble registering it with my GIMP 2.10 on macOS 10.15.7. I have run your install validation script (/path/to/python3/python ./seganybridge.py vit_h /path/to/checkpoint/model/sam_vit_h_4b8939.pth) and got a Success. I have put the seganybridge.py and seganyplugin.py in the /Users/me/Library/Application Support/GIMP/2.10/plug-ins repository. I also changed the mode so that these files are executable (chmod 777). Made sure I restarted GIMP. I also made sure SAM was properly installled by running the script amg.py from the SAM github and generated the segmentation masks. So seems my only trouble is registering your plugin with GIMP. Do you have any idea why it is not registering with GIMP and would you know of any way to check/debug the registration process ?

**Comment by Shriinivas** [comment]
I have modified the script on github to accept spaces in the directory, please use the new script. Here are a couple other things to note 
1) Make sure the segment-anything folder you created with git clone is in the PYTHONPATH 
2) You need to have Python-Fu enabled. Also, check the python version from Python-Fu console, it should be 2.7.x. The script will run with only python2 since, to my knowledge, GIMP 2.10 has not yet upgraded to python3. Please let me know if you still face any issues.
3) You should make only seganyplugin.py executable, making the other also executable won't break anything, but you would get an error on console after start-up.

Since GIMP 2.10 works with python2 and Segment Anything needs Python3, I am calling the seganybridge as an OS command from within python. So it's important that python2 and python3 are on your system and you specify the python3 path used by Segment Anything in the pop-up dialog of the plugin.

**Comment by 8o050** [comment]
Thank you so much for creating this plugin! 

I had to make a couple of modifications to make this work on my mac (M3).  The gimp version is 2.10.36 when I am writing this. I am using miniconda to set the SegmentAnything model up.

0. I ran the GIMP in the terminal to get the errors. Otherwise, it just silently fails to load:

```
/Applications/GIMP.app/Contents/MacOS/gimp --verbose
```

1. Add the following lines to the top of the `seganyplugin.py` just like other plugins like gradients-save-as-css: 

```
#! /usr/bin/env python
# -*- coding: utf-8 -*-
```

Without this, GIMP was giving me an error like this.

```
GIMP-WARNING: gimp: gimp_wire_read(): error
```

2. Clear the `env_vars` with the `shellRun`. In `seganyplugin.py` , I modified the following lines to pass `env_vars`:

```
    env_vars = {
        'PYTHONPATH': ""
    }
    shellRun(cmd, env_vars=env_vars)
```

Without this, there was a `numpy` conflict error like these:

```
2024-02-10 13:07:27 - INFO - Running command: /Users/user/miniconda3/envs/gimp/bin/python /Applications/GIMP.app/Contents/Resources/lib/gimp/2.0/plug-ins/seganyplugin/seganybridge.py vit_h /Users/user/Documents/segment_anything/sam_vit_h_4b8939.pth /var/folders/3l/.../T/__seg__5GZQCr.png Selection Multiple /var/folders/3l/.../T/__seg__mask__ True /var/folders/3l/.../T/__seg__sel__.txt
2024-02-10 13:07:27 - ERROR - Command failed with the following error:
 Traceback (most recent call last):
  File "/Applications/GIMP.app/Contents/Resources/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/Applications/GIMP.app/Contents/Resources/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/multiarray.py", line 13, in <module>
    from . import overrides
  File "/Applications/GIMP.app/Contents/Resources/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Applications/GIMP.app/Contents/Resources/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so, 0x0002): symbol not found in flat namespace '_PyBuffer_Type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/GIMP.app/Contents/Resources/lib/gimp/2.0/plug-ins/seganyplugin/seganybridge.py", line 24, in <module>
    import torch
  File "/Users/user/miniconda3/envs/gimp/lib/python3.9/site-packages/torch/__init__.py", line 1209, in <module>
    from .storage import _StorageBase, TypedStorage, _LegacyStorage, UntypedStorage, _warn_typed_storage_removal
  File "/Users/user/miniconda3/envs/gimp/lib/python3.9/site-packages/torch/storage.py", line 14, in <module>
    import numpy as np
  File "/Applications/GIMP.app/Contents/Resources/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Applications/GIMP.app/Contents/Resources/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /Users/user/miniconda3/envs/gimp/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: dlopen(/Applications/GIMP.app/Contents/Resources/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so, 0x0002): symbol not found in flat namespace '_PyBuffer_Type'


2024-02-10 13:07:27 - DEBUG - Finished creating segments!
```

Hope this helps someone!

**Comment by Popshells** [comment]
Hi, thank you for this! I followed all these guidelines and I got the "Success!" message in the console after running seganybridge.py in my M1, made seganyplugin.py executable and added `export PYTHONPATH="/path/to/segment-anything:$PYTHONPATH"` to my SAM-env activate command, the venv has pytorch.org/whl/nightly/cpu , but the plugin crashes starting up Gimp 2.10.38 (revision 1), the following error is from the terminal and I don't know how to troubleshoot it, any suggestions are welcome, thank you in advance: 

```
Querying plug-in: '/Users/me/Library/Application Support/GIMP/2.10/plug-ins/seganyplugin.py'
/Applications/GIMP.app/Contents/MacOS/gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
Terminating plug-in: '/Users/me/Library/Application Support/GIMP/2.10/plug-ins/seganyplugin.py'
```

**Comment by Shriinivas** [comment]
Hi @Popshells I suppose your issue is fixed after adding shebang as suggested by @8o050, if not please let me know. I have been avoiding installing python GIMP since the latest re-installion of OS as python 2 is outdated (discontinued since 2020) and installing it on Linux is quite a bit of a hassle. And don't want to include anything that I have not tested on my machine, so not including this change in the code for now. I hope GIMP 3 arrives soon with its python 3 support. That would make this plugin much simpler and a lot more streamlined.

**Comment by Popshells** [comment]
Thanks for the rapid response! Yes! After adding the shebang at the very top, and replacing `shellRun(cmd)` as @8o050 suggested it's working fine! Thank you! Awesome tool integration!

**Comment by csites** [comment]
Just to add to this, I've been rewriting the plugin for Gimp 3.0 (currently 3.0RC3).   I'm in the testing stage right now.    There are a lot of changes required for Gimp 3.0 but all are located in seganyplugin.py.  The seganybridge.py works without change.   I have to say, it's one of the coolest and most useful plugins I've seen.   I would love to see something like this for Inkscape.

**Comment by mpEsri** [comment]
> Just to add to this, I've been rewriting the plugin for Gimp 3.0 (currently 3.0RC3). I'm in the testing stage right now. There are a lot of changes required for Gimp 3.0 but all are located in seganyplugin.py. The seganybridge.py works without change. I have to say, it's one of the coolest and most useful plugins I've seen. I would love to see something like this for Inkscape.

Hi, I'd like to try your Gimp 3.x plugin. Is it available for testing?

**Comment by csites** [comment]
seganypluging.py for gimp3.0 is not an easy install, and I have it set up in my personal "venv" environment.    I do have the plugin for gimp 3.0  working, and the GUI portion of the plugin looks OK.  The problems I had were with CUDA  and GPU memory on my large test images.   There were other issues, too.   It's about 60% of the way there.   I abandoned the work as                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 I felt it was distracting me from my goal of auto-segmenting and classifying golf course layouts.   However, I've been really impressed by SAM and I can see its usefulness to the community.     So maybe it would be worth re-exploring.  Anyway, I've uploaded and created a github repository with the code as it currently exists; https://github.com/csites/gimp3segany

**Comment by Shriinivas** [comment]
@mpEsri @csites I have updated the plugin for GIMP3 (thanks to AI :), please check the readme for the new installation and usage instructions. Please test and let me know.

**Comment by csites** [comment]
I was testing the new code @Shriinivas, and it appears that when selecting the box, there is a minor issue with the args position passed to the seganybridge.py.     I think you want this line 274;  boxCos = [float(val.strip()) for val in sys.argv[9].split(',')].   Now, if I can figure out how to show and view the layers it has segmented.  Lol.

**Comment by csites** [comment]
@Shriinivas, after looking at the function createLayer in your GIMP2 version and the GIMP3 version, I called in a little Gemini AI help to see if this was stopping it from displaying the layers.    It fixed it and it works well.   Here is the revised createLayer function for the seganyplugin.py.  
``
def createLayers(image, maskFileNoExt, userSelColor, formatBinary, values):
    width, height = image.get_width(), image.get_height()

    idx = 0
    maxLayers = 99999

    parent = Gimp.GroupLayer.new(image)
    parent.set_name(f"Segment Anything - {values.segType}")
    image.insert_layer(parent, None, 0)
    parent.set_opacity(50)

    uniqueColors = getRandomColor(layerCnt=999)

    if image.get_base_type() == Gimp.ImageType.GRAYA_IMAGE:
        layerType = Gimp.ImageType.GRAYA_IMAGE
        userSelColor = [100, 255]
        babl_format = "YA u8"
        pix_size = 2
    else:
        layerType = Gimp.ImageType.RGBA_IMAGE
        babl_format = "RGBA u8"
        pix_size = 4

    while idx < maxLayers:
        filepath = maskFileNoExt + str(idx) + ".seg"
        if exists(filepath):
            print("Creating Layer..", (idx + 1))
            newlayer = Gimp.Layer.new(
                image,
                f"Mask - {values.segType} #{idx + 1}",
                width,
                height,
                layerType,
                100.0,
                Gimp.LayerMode.NORMAL,
            )
            image.insert_layer(newlayer, parent, 0)
            newlayer.set_visible(True) # Make the layer visible

            buffer = newlayer.get_buffer()
            rect = Gegl.Rectangle.new(0, 0, width, height)

            maskVals = readMaskFile(filepath, formatBinary)
            maskColor = (
                userSelColor
                if userSelColor is not None
                else list(uniqueColors[idx]) + [255]
            )

            mask_color_bytes = bytes(maskColor)
            
            # --- FIX: Populate a single bytearray instead of a list of strings
            pixels = bytearray(width * height * pix_size)
            for x, row in enumerate(maskVals):
                for y, p in enumerate(row):
                    if p:
                        pos = (y + width * x) * pix_size
                        pixels[pos: pos + pix_size] = mask_color_bytes
            
            buffer.set(rect, babl_format, bytes(pixels))
            # --- END FIX

            idx += 1
            newlayer.update(0, 0, width, height)
        else:
            break

    return idx
``

I'm now getting some beautiful segmentation results with the GIMP3 plugin.    On minor addition that would be nice in the dialog would be the ability to change the Alpha value, which I think defaults to 50%.    Best regards.

**Comment by mpEsri** [comment]
Wow! Great work. I'll test it out. Thanks you so much for this.

**Comment by Shriinivas** [comment]
@csites Could you tell me what error you encounter without the changes you proposed. The change to generate layer functionality is related to optimizing the pixel manipulation using GIMP3 APIs (instead of using the old approach, which is slightly inefficient). The plugin is working fine with me without any changes and generating quite good results.I have also added option for SAM1 segmentation since the default SAM1 behavior detects more segments, which might be useful in some situations. 

BTW I have also created an Inkscape extension with similar functionality (generate SVG paths): https://github.com/Shriinivas/inksegany

**Comment by csites** [comment]
Sure, The first error that shows up for me is in the seganybridge.   Steps to reproduce: run gimp and load an image.  Using Tools > Selection Tools > Rectangle Select and select a box in the image.    Next, go to the plugin, Image > Segment Anything Layers.   Put the Segmentation Type:  Box.  The OK.    That generates this message;  

2025-08-19 08:59:39 - INFO - Running command: /home/chuck/venv/bin/python3 /home/chuck/.config/GIMP/3.0/plug-ins/segany/seganybridge.py sam2_hiera_small /home/chuck/.config/GIMP/3.0/plug-ins/segany/sam2_hiera_small.pt /tmp/__seg__nccs6pbs.png Box Multiple /tmp/__seg__mask__ True sel_place_holder 583,610,616,640
Model loaded successfully!

Model moved to CUDA

2025-08-19 08:59:42 - ERROR - Command failed with the following error:
 Traceback (most recent call last):
  File "/home/chuck/.config/GIMP/3.0/plug-ins/segany/seganybridge.py", line 284, in <module>
    main()
    ~~~~^^
  File "/home/chuck/.config/GIMP/3.0/plug-ins/segany/seganybridge.py", line 270, in main
    boxCos = [float(val.strip()) for val in sys.argv[8].split(',')]
              ~~~~~^^^^^^^^^^^^^
ValueError: could not convert string to float: 'sel_place_holder'

2025-08-19 08:59:42 - DEBUG - Finished creating segments!
set device 'Logitech USB-PS/2 Optical Mouse' to mode: disabled
set device 'Logitech USB-PS/2 Optical Mouse' to mode: disabled
set device 'Logitech USB-PS/2 Optical Mouse' to mode: disabled
set device 'Logitech USB-PS/2 Optical Mouse' to mode: disabled
[seg-any-gimp3] The catalog directory does not exist: /home/chuck/.config/GIMP/3.0/plug-ins/segany/locale
[seg-any-gimp3] Override method set_i18n() for the plug-in to customize or disable localization.
[seg-any-gimp3] Localization disabled

***  NOTE:  I've never figured out why that Localization message gets displayed.   It was doing that to me in other plugins.   
*** Backtracking the issue it points to line 620 if seganyplugin.py for the function run_segmentation in the values.segType == "Box".   cmd.append("sel_place_holder").  The fix is simply to chage the sys.argv[8].split*',') to sys.argv[9].slit(',') in the seganybridge.py code.

**Comment by csites** [comment]
As far as the second fix in the seganyplugin.py, what was happening when I ran any of the Segmentation types, let's pick 'Auto' for example, the plugin would run without errors, launch CUDA,  create layers, and finish.   However, the gimp screen would never update the display and show the masks.  Basically, it spun its wheels but didn't do anything.   I thought it might be the newlayer.set_visible(False) in the def createLayers function.   But setting that event to True didn't fix the issue.   Looking, I could see that it had created a series of filenames ending with the extension .seg, but it just didn't look like it was updating the layers.   Anyway,  so this is where I asked Gemini to assist, and it recommended that fix, which worked for me.    It looks like an update of the image.insert_layer(newlayer, parent, 0) after the byffer is retrieved in buffer = newlayer.getbuffer() needed to occur.    It behaves nicely now and functions as expected on my machine (kubuntu 25.04, Python 3.13.3,  CUDA 12.8, and Gimp 3.0.2 ).

**Comment by Shriinivas** [comment]
@csites Thanks for your fixes, I have included both of them in the code. Kindly test with the new code. Closing this issue now. You can open a new one for this or any other issues you face.

**Comment by csites** [comment]
Thank you, Shriinivas, for the updates.   It looks good.   For some reason, it was still not showing the layers after segmentation.     I had to check the box for 'Crop n Layers' before it would display the segmentation.    But with that enabled, it works fine.    I'm not clear as to what 'Crop n Layers' is supposed to do.   But that fixed it for me.   One feature suggestion that would be useful would be a field that prompts for Percent Opacity:  50.  Its value would be  from 0 to 100.    Then use that as the alpha value for the segmented regions (Alpha = int(255.0 * (Percent Opacity/100.0)).
